apiVersion: v2
name: postgres
version: "0.0.3"
description: A Helm chart for PostgreSQL on Kubernetes
maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
  - name: floriansipp
    email: florian.sipp@chuv.ch
dependencies:
  - name: postgres
    version: "1.6.2"
    repository: https://groundhog2k.github.io/helm-charts/
