mlflow:
  postgresql:
    enabled: false
  mysql:
    enabled: false
  backendStore:
    databaseMigration: true
    databaseConnectionCheck: true
    postgres:
      enabled: true
      port: 5432
      database: mlflow
      user: mlflow
  artifactRoot:
    proxiedArtifactStorage: true
  log:
    enabled: false
  extraArgs:
    host: "0.0.0.0"
    allowedHosts: "*"
    uvicornOpts: "--log-level info"
  extraVolumes:
    - name: artifacts
  extraVolumeMounts:
    - name: artifacts
      mountPath: /mlflow/mlartifacts

artifactStorage:
  size: 10Gi

postgres:
  nameOverride: "mlflow-db"
  settings:
    superuser:
      value: postgres
  userDatabase:
    name:
      value: mlflow
    user:
      value: mlflow
  storage:
    requestedSize: 5Gi
