apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ (index .Values.mlflow.extraVolumes 0).persistentVolumeClaim.claimName }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.artifactStorage.size }}
