apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.artifactStorage.size }}
